Lesson 5 - Creating and managing `ndarray`

In [ ]:
import numpy as np

## Creating ndarray using built-in method

In [ ]:
# matrix of zeros
zeros_matrix = np.zeros((3,4))
zeros_matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# matrix of ones
ones_matrix = np.ones((3,2))
ones_matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
full_matrix = np.full((2,3), 5)
full_matrix

array([[5, 5, 5],
       [5, 5, 5]])

In [ ]:
print(f'Element type of zeros_matrix: {zeros_matrix.dtype}')
print(f'Element type of ones_matrix: {ones_matrix.dtype}')
print(f'Element type of ones_matrix: {full_matrix.dtype}')

Element type of zeros_matrix: float64
Element type of ones_matrix: float64
Element type of ones_matrix: int64


In [ ]:
#Identity matrix
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
diagonal_matrix = np.diag([1,2,3,4])
diagonal_matrix

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
#using arange
vect1 = np.arange(10)
vect1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
vect2 = np.arange(4.1, 9)
vect2

array([4.1, 5.1, 6.1, 7.1, 8.1])

In [ ]:
vect = np.arange(1,14,3)
vect

array([ 1,  4,  7, 10, 13])

A good alternative to `np.arange` is `np.linspace` function which works better than `np.arange` due to the finite floating point precision.

Moreover, `np.linspace` uses the number of elements we want in a particular interval, instead of the step between values.

In [ ]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25.
vect3 = np.linspace(0,25,10)
vect3

array([ 0.        ,  2.77777778,  5.55555556,  8.33333333, 11.11111111,
       13.88888889, 16.66666667, 19.44444444, 22.22222222, 25.        ])

In [ ]:
# using np.random.random
rand_matrix = np.random.random((3,3))
rand_matrix

array([[0.38092162, 0.22859676, 0.96004006],
       [0.6855616 , 0.70534742, 0.05605433],
       [0.72397115, 0.40938473, 0.94926686]])

In [ ]:
# using np.random.randint
rand_matrix = np.random.randint(4, 13, (3,3))
rand_matrix

array([[ 6,  9,  8],
       [11, 11,  6],
       [12,  4,  6]])

In [ ]:
# We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.
X = np.random.normal(0, 0.1, size=(1000,1000))

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')

X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: 4.259648934252423e-05
The maximum value in X is: 0.47986332291984274
The minimum value in X is: -0.4519409436150761
X has 499484 negative numbers
X has 500516 positive numbers


## Reshape operation

In [ ]:
# from vector to matrix
vector = np.arange(20)
vect2matrix = np.reshape(vector, (4,5))
vect2matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
#from matrix to vector by row 'C-style'
vect2matrix.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
vect2matrix.flatten(order='F')

array([ 0,  5, 10, 15,  1,  6, 11, 16,  2,  7, 12, 17,  3,  8, 13, 18,  4,
        9, 14, 19])

## Accessing, Deleting and Inserting elements 

Accessing data in a vector and matrix

In [ ]:
# accessing data in a vector
vect = np.array([1, 2, 3, 4, 5])
print('Third element in vect:', vect[2])
print('Last element in vect:', vect[-1])

Third element in vect: 3
Last element in vect: 5


In [ ]:
# accessing data in a matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Element in position (0,1):', matrix[0,1])

Element in position (0,1): 2


Deleting data from a vector and matrix

In [ ]:
np.delete(vect, [0,2])

array([2, 4, 5])

In [ ]:
# deleting a row (set axis to 0)
np.delete(matrix, [0,0], axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
# deleting a column (set axis to 1)
np.delete(matrix, [0,0], axis=1)

array([[2, 3],
       [5, 6],
       [8, 9]])

Appending data to vector and matrix

In [ ]:
np.append(vect, 6)

array([1, 2, 3, 4, 5, 6])

In [ ]:
# on the row
np.append(matrix, [[10, 11, 12]], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# on the column
np.append(matrix, [[10], [11], [12]], axis=1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

Inserting data into a vector or matrix

In [ ]:
# insert elements before index vect[2]
np.insert(vect, 2, [10, 11])

array([ 1,  2, 10, 11,  3,  4,  5])

In [ ]:
np.insert(matrix,1,[10,11,12],axis=0)

array([[ 1,  2,  3],
       [10, 11, 12],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
np.insert(matrix,1,1, axis=1)

array([[1, 1, 2, 3],
       [4, 1, 5, 6],
       [7, 1, 8, 9]])