<a href="https://colab.research.google.com/github/antedesk/numpy-htmlit/blob/main/lesson3_data_types.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lesson 3 - Data Types


## Importing numpy

In [17]:
import numpy as np

## Defintion of a dtype object

In [18]:
dt_int32 = np.dtype('int32')

# equivalent alternative
dt_int32_v2 = np.dtype(np.int32)

In [19]:
dt_int32

dtype('int32')

In [20]:
dt_int32_v2

dtype('int32')

## dtype attribute 

Check if the `dt_int32` is a built-in data type

For additional info check the [the official documentation](https://numpy.org/doc/stable/reference/generated/numpy.dtype.isbuiltin.html#numpy.dtype.isbuiltin)

In [21]:
dt_int32.isbuiltin

1

## Data conversion using data-types as conversion functions

**Conversion of an int value to float**

In [22]:
x = np.float32(1)

In [23]:
x

1.0

**Conversion of an array of int values to an array of float**





In [24]:
floatarray = np.float_([1,2,4])

In [25]:
floatarray

array([1., 2., 4.])

**Creation of an array of complex64 values**

In [26]:
array_dtype_complex64 = np.arange(3, dtype=np.complex64)

In [27]:
array_dtype_complex64

array([0.+0.j, 1.+0.j, 2.+0.j], dtype=complex64)

In [28]:
array_dtype_complex64.dtype

dtype('complex64')

## Array-protocol type strings

**Definition of a 32-bit signed integer**

In [29]:
dt = np.dtype('i4')   # 32-bit signed integer
dt

dtype('int32')

**Definition of a 64-bit floating-point number**

In [30]:
dt = np.dtype('f8')   # 64-bit floating-point number
dt

dtype('float64')

**Creation of an array composed of 3 complex16 values**

In [31]:
complex_array = np.arange(3, dtype=np.dtype('c16'))
complex_array

array([0.+0.j, 1.+0.j, 2.+0.j])

In [32]:
complex_array.dtype

dtype('complex128')