In [1]:
import numpy as np

## Stacking

In [2]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[5,6],[7,8]]) 
v1 = np.array((1,2,3))
v2 = np.array((4,5,6))

### stack() ndarrays 

In [3]:
np.stack((v1,v2),axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.stack((v1,v2),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
np.stack((a,b),axis=0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [6]:
np.stack((a,b),axis=1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

### vstack() ndarrays 

In [7]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### hstack() ndarrays 

In [8]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### dstack() ndarrays 

In [9]:
np.dstack((a,b))

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

## Splitting

### 1D ndarray split()

In [10]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.split(x, 5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

### 2D ndarray split()

In [12]:
np.split(x, [4, 6, 7])

[array([0, 1, 2, 3]), array([4, 5]), array([6]), array([7, 8, 9])]

In [13]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
np.split(m, [1,3])

[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]

### 2D ndarray array_split

In [15]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
np.array_split(m,3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]

### 2d ndarray hsplit()

In [17]:
m1 = np.arange(20).reshape(5, 4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [18]:
np.hsplit(m1,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]), array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17]]), array([[ 2],
        [ 6],
        [10],
        [14],
        [18]]), array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

### 2d ndarray vsplit()

In [19]:
m1 = np.arange(24).reshape(6, 4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
np.vsplit(m1,3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]), array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

### 3D ndarray dsplit()

In [21]:
t = np.arange(24).reshape(2, 2, 6)
t

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [22]:
np.dsplit(t, [2, 4])

[array([[[ 0,  1],
         [ 6,  7]],
 
        [[12, 13],
         [18, 19]]]), array([[[ 2,  3],
         [ 8,  9]],
 
        [[14, 15],
         [20, 21]]]), array([[[ 4,  5],
         [10, 11]],
 
        [[16, 17],
         [22, 23]]])]