In [1]:
import numpy as np

### ndarray access and indexing

In [30]:
# 1D ndarray
vect = np.array([1, 2, 3, 4])
vect[2]

3

In [31]:
# 2D ndarray
matrix = np.random.randint(1, 13, (3,3))
matrix[1][2]

3

In [32]:
# 3D ndarray
tensor = np.random.randint(1,100, (4,4,4))
tensor[1][3][2]

38

In [33]:
tensor

array([[[44, 34, 89, 23],
        [40, 98, 62, 85],
        [50, 24, 63, 36],
        [47, 37, 83, 71]],

       [[59, 38, 76, 82],
        [99, 89, 70, 51],
        [30, 17, 64, 52],
        [35, 24, 38, 73]],

       [[73, 28, 40, 50],
        [48, 51, 67, 81],
        [88, 81, 87, 57],
        [ 9, 65, 59,  7]],

       [[32, 18,  9, 55],
        [43,  3, 53, 96],
        [30, 91, 60, 53],
        [82, 15, 98, 68]]])

In [34]:
# negative indexing on matrix
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
#get last element of the second row
m[1][-1]

6

In [35]:
# negative indexing on tensor
tensor[-1][2][3]

53

### slicing

The basic slice syntax is `i:j:k` where: 
- `i` is the starting index
- `j` is the stopping index 
- `k` is the step 

This values can be positive or negative.

Let's see some examples

In [36]:
v = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
v[1:8:2]

array([1, 3, 5, 7])

Negative `i` and `j` are interpreted as `n+i` and `n+j` where `n` is the number of elements in the corresponding dimension. 


In [37]:
v[-3:9]

array([7, 8])

In [38]:
v[-3:3:-1]

array([7, 6, 5, 4])

In [39]:
v[-1]

9

In [40]:
v[-3:3:-1]

array([7, 6, 5, 4])

In [41]:
v[6:]

array([6, 7, 8, 9])

In [42]:
#all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
m = np.arange(20).reshape(4, 5)
m[1:4,2:5]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [43]:
#select all the elements that are in the 1st through 3rd rows and in the 3rd to 4th columns
m[:3,2:5]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

### Ellipsis

`Ellipsis` expands to the number of `:` objects needed for the selection tuple to index all dimensions. 

In most cases, this means that length of the expanded selection tuple is `x.ndim`. There may only be a single ellipsis present.

In [22]:
m[...,0]

array([1, 4, 7])

In [23]:
m[2,...]

array([7, 8, 9])

In [24]:
# get first col of each tensor's matrix
tensor[...,0]

array([[ 3, 17, 96, 98],
       [87, 25, 91, 29],
       [45, 74, 17, 24],
       [70,  5, 24, 88]])

In [25]:
# get first tensor's matrix
tensor[0,...]

array([[ 3,  2, 29, 56],
       [17, 46, 47, 87],
       [96, 51, 54, 21],
       [98, 97, 19, 38]])

In [26]:
tensor[1,...,2]

array([56, 52, 16, 90])

In [27]:
# the equivalent
tensor[1,:,2]

array([56, 52, 16, 90])

### Copy ndarray


if we want to create a new `ndarray` that contains a copy of the values in the slice we need to use the `np.copy()` function. The `np.copy(ndarray)` function creates a copy of the given `ndarray`. 

In [44]:

X = np.copy(m[1:4,2:5])

In [45]:
X[2,2] = 555

In [46]:
print(f'{X[2,2]} != {m[2,2]}')

555 != 12


In [47]:
x=m[1:4,2:5]

In [48]:
m[2,2] =213456
print(f'{x[1,0]} != {m[2,2]}')

213456 != 213456


#### Slicing vs Indexing

In [49]:
#indexing
m = np.array([[10, 11, 12, 13, 14],
               [15, 16, 17, 18, 19],
               [20, 21, 22, 23, 24],
               [25, 26, 27, 28, 29]])

print(m[1,2:4])  

[17 18]


In [50]:
#slicing
print(m[1:2,2:4])

[[17 18]]


### Boolean indexing

In [51]:
# 5 x 5 ndarray that contains integers from 0 to 24
matrix = np.arange(25).reshape(5, 5)

In [55]:
# We use Boolean indexing to select elements in matrix:
print('The elements in matrix that are greater than 10:', matrix[matrix > 10])
print('The elements in matrix that less than or equal to 7:', matrix[matrix <= 7])
print('The elements in matrix that are between 9 and 15:', matrix[(matrix > 9) & (matrix < 15)])

The elements in matrix that are greater than 10: [15 16 17 18 19 20 21 22 23 24]
The elements in matrix that less than or equal to 7: [ 0  1  2  3  4  5  6  7 -1 -1 -1 -1 -1]
The elements in matrix that are between 9 and 15: []


In [56]:
# We use Boolean indexing to assign the elements that are between 10 and 17 the value of -1
matrix[(matrix > 9) & (matrix < 15)] = -1
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [-1, -1, -1, -1, -1],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
my_mask=(matrix > 10) & (matrix < 17)
matrix[my_mask]

array([15, 16])